services:
  agent-zero:
    container_name: agent-zero
    image: agent0ai/agent-zero:latest
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
    volumes:
      - ./agent-zero:/a0
    ports:
      - "50080:80"